version: "3.9"

services:
  main_scores:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8777:5000"
    volumes:
      - C:/Users/manor/Desktop/Python/WorldOfGames/Scores.txt:/Scores.txt

